apiVersion: v1
kind: Service
metadata:
  name: cars-v1
  namespace: travel-agency
  labels:
    app: cars
    version: v1
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: cars
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: cars-v2
  namespace: travel-agency
  labels:
    app: cars
    version: v2
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: cars
    version: v2