kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
  namespace: istio-system
spec:
  to:
    kind: Service
    name: grafana
    weight: 100
  port:
    targetPort: service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
