apiVersion: sailoperator.io/v1
kind: ZTunnel
metadata:
  name: default
spec:
  namespace: ztunnel
  values:
    ztunnel:
      logLevel: info
      terminationGracePeriodSeconds: 30
  version: v1.27-latest
  profile: ambient